schema: src/**/*.graphql
generates:
  ./src/resolvers-types.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      useIndexSignature: true
    hooks:
      afterOneFileWrite:
        - prettier --write
        - eslint --fix
